/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.api;

import io.github.mike_rollout.ApiCallback;
import io.github.mike_rollout.ApiClient;
import io.github.mike_rollout.ApiException;
import io.github.mike_rollout.ApiResponse;
import io.github.mike_rollout.Configuration;
import io.github.mike_rollout.Pair;
import io.github.mike_rollout.ProgressRequestBody;
import io.github.mike_rollout.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.github.mike_rollout.model.Error;
import io.github.mike_rollout.model.PublicMergeInput;
import io.github.mike_rollout.model.SimplePublicObject;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PublicObjectApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PublicObjectApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PublicObjectApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for postCrmV3ObjectsContactsMergeMerge
     * @param publicMergeInput  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> An error occurred. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postCrmV3ObjectsContactsMergeMergeCall(PublicMergeInput publicMergeInput, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = publicMergeInput;

        // create path and map variables
        String localVarPath = "/crm/v3/objects/contacts/merge";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "*/*"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "oauth2", "private_apps" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call postCrmV3ObjectsContactsMergeMergeValidateBeforeCall(PublicMergeInput publicMergeInput, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'publicMergeInput' is set
        if (publicMergeInput == null) {
            throw new ApiException("Missing the required parameter 'publicMergeInput' when calling postCrmV3ObjectsContactsMergeMerge(Async)");
        }

        return postCrmV3ObjectsContactsMergeMergeCall(publicMergeInput, _callback);

    }

    /**
     * Merge two contacts with same type
     * 
     * @param publicMergeInput  (required)
     * @return SimplePublicObject
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> An error occurred. </td><td>  -  </td></tr>
     </table>
     */
    public SimplePublicObject postCrmV3ObjectsContactsMergeMerge(PublicMergeInput publicMergeInput) throws ApiException {
        ApiResponse<SimplePublicObject> localVarResp = postCrmV3ObjectsContactsMergeMergeWithHttpInfo(publicMergeInput);
        return localVarResp.getData();
    }

    /**
     * Merge two contacts with same type
     * 
     * @param publicMergeInput  (required)
     * @return ApiResponse&lt;SimplePublicObject&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> An error occurred. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<SimplePublicObject> postCrmV3ObjectsContactsMergeMergeWithHttpInfo(PublicMergeInput publicMergeInput) throws ApiException {
        okhttp3.Call localVarCall = postCrmV3ObjectsContactsMergeMergeValidateBeforeCall(publicMergeInput, null);
        Type localVarReturnType = new TypeToken<SimplePublicObject>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Merge two contacts with same type (asynchronously)
     * 
     * @param publicMergeInput  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> successful operation </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> An error occurred. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call postCrmV3ObjectsContactsMergeMergeAsync(PublicMergeInput publicMergeInput, final ApiCallback<SimplePublicObject> _callback) throws ApiException {

        okhttp3.Call localVarCall = postCrmV3ObjectsContactsMergeMergeValidateBeforeCall(publicMergeInput, _callback);
        Type localVarReturnType = new TypeToken<SimplePublicObject>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
