/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mike_rollout.model.SimplePublicObjectBatchInput;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.mike_rollout.JSON;

/**
 * BatchInputSimplePublicObjectBatchInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-19T16:43:10.955404+03:00[Africa/Nairobi]", comments = "Generator version: 7.7.0")
public class BatchInputSimplePublicObjectBatchInput {
  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private List<SimplePublicObjectBatchInput> inputs = new ArrayList<>();

  public BatchInputSimplePublicObjectBatchInput() {
  }

  public BatchInputSimplePublicObjectBatchInput inputs(List<SimplePublicObjectBatchInput> inputs) {
    this.inputs = inputs;
    return this;
  }

  public BatchInputSimplePublicObjectBatchInput addInputsItem(SimplePublicObjectBatchInput inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

  /**
   * Get inputs
   * @return inputs
   */
  @javax.annotation.Nonnull
  public List<SimplePublicObjectBatchInput> getInputs() {
    return inputs;
  }

  public void setInputs(List<SimplePublicObjectBatchInput> inputs) {
    this.inputs = inputs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput = (BatchInputSimplePublicObjectBatchInput) o;
    return Objects.equals(this.inputs, batchInputSimplePublicObjectBatchInput.inputs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchInputSimplePublicObjectBatchInput {\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("inputs");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("inputs");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BatchInputSimplePublicObjectBatchInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BatchInputSimplePublicObjectBatchInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BatchInputSimplePublicObjectBatchInput is not found in the empty JSON string", BatchInputSimplePublicObjectBatchInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BatchInputSimplePublicObjectBatchInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BatchInputSimplePublicObjectBatchInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BatchInputSimplePublicObjectBatchInput.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("inputs").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `inputs` to be an array in the JSON string but got `%s`", jsonObj.get("inputs").toString()));
      }

      JsonArray jsonArrayinputs = jsonObj.getAsJsonArray("inputs");
      // validate the required field `inputs` (array)
      for (int i = 0; i < jsonArrayinputs.size(); i++) {
        SimplePublicObjectBatchInput.validateJsonElement(jsonArrayinputs.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BatchInputSimplePublicObjectBatchInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BatchInputSimplePublicObjectBatchInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BatchInputSimplePublicObjectBatchInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BatchInputSimplePublicObjectBatchInput.class));

       return (TypeAdapter<T>) new TypeAdapter<BatchInputSimplePublicObjectBatchInput>() {
           @Override
           public void write(JsonWriter out, BatchInputSimplePublicObjectBatchInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BatchInputSimplePublicObjectBatchInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BatchInputSimplePublicObjectBatchInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BatchInputSimplePublicObjectBatchInput
   * @throws IOException if the JSON string is invalid with respect to BatchInputSimplePublicObjectBatchInput
   */
  public static BatchInputSimplePublicObjectBatchInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BatchInputSimplePublicObjectBatchInput.class);
  }

  /**
   * Convert an instance of BatchInputSimplePublicObjectBatchInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

