/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mike_rollout.model.ForwardPaging;
import io.github.mike_rollout.model.SimplePublicObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.mike_rollout.JSON;

/**
 * CollectionResponseWithTotalSimplePublicObjectForwardPaging
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-19T16:43:10.955404+03:00[Africa/Nairobi]", comments = "Generator version: 7.7.0")
public class CollectionResponseWithTotalSimplePublicObjectForwardPaging {
  public static final String SERIALIZED_NAME_TOTAL = "total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public static final String SERIALIZED_NAME_PAGING = "paging";
  @SerializedName(SERIALIZED_NAME_PAGING)
  private ForwardPaging paging;

  public static final String SERIALIZED_NAME_RESULTS = "results";
  @SerializedName(SERIALIZED_NAME_RESULTS)
  private List<SimplePublicObject> results = new ArrayList<>();

  public CollectionResponseWithTotalSimplePublicObjectForwardPaging() {
  }

  public CollectionResponseWithTotalSimplePublicObjectForwardPaging total(Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @javax.annotation.Nonnull
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  public CollectionResponseWithTotalSimplePublicObjectForwardPaging paging(ForwardPaging paging) {
    this.paging = paging;
    return this;
  }

  /**
   * Get paging
   * @return paging
   */
  @javax.annotation.Nullable
  public ForwardPaging getPaging() {
    return paging;
  }

  public void setPaging(ForwardPaging paging) {
    this.paging = paging;
  }


  public CollectionResponseWithTotalSimplePublicObjectForwardPaging results(List<SimplePublicObject> results) {
    this.results = results;
    return this;
  }

  public CollectionResponseWithTotalSimplePublicObjectForwardPaging addResultsItem(SimplePublicObject resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<>();
    }
    this.results.add(resultsItem);
    return this;
  }

  /**
   * Get results
   * @return results
   */
  @javax.annotation.Nonnull
  public List<SimplePublicObject> getResults() {
    return results;
  }

  public void setResults(List<SimplePublicObject> results) {
    this.results = results;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CollectionResponseWithTotalSimplePublicObjectForwardPaging collectionResponseWithTotalSimplePublicObjectForwardPaging = (CollectionResponseWithTotalSimplePublicObjectForwardPaging) o;
    return Objects.equals(this.total, collectionResponseWithTotalSimplePublicObjectForwardPaging.total) &&
        Objects.equals(this.paging, collectionResponseWithTotalSimplePublicObjectForwardPaging.paging) &&
        Objects.equals(this.results, collectionResponseWithTotalSimplePublicObjectForwardPaging.results);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, paging, results);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CollectionResponseWithTotalSimplePublicObjectForwardPaging {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    paging: ").append(toIndentedString(paging)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("total");
    openapiFields.add("paging");
    openapiFields.add("results");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("total");
    openapiRequiredFields.add("results");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CollectionResponseWithTotalSimplePublicObjectForwardPaging
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CollectionResponseWithTotalSimplePublicObjectForwardPaging.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CollectionResponseWithTotalSimplePublicObjectForwardPaging is not found in the empty JSON string", CollectionResponseWithTotalSimplePublicObjectForwardPaging.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CollectionResponseWithTotalSimplePublicObjectForwardPaging.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CollectionResponseWithTotalSimplePublicObjectForwardPaging` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CollectionResponseWithTotalSimplePublicObjectForwardPaging.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `paging`
      if (jsonObj.get("paging") != null && !jsonObj.get("paging").isJsonNull()) {
        ForwardPaging.validateJsonElement(jsonObj.get("paging"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("results").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `results` to be an array in the JSON string but got `%s`", jsonObj.get("results").toString()));
      }

      JsonArray jsonArrayresults = jsonObj.getAsJsonArray("results");
      // validate the required field `results` (array)
      for (int i = 0; i < jsonArrayresults.size(); i++) {
        SimplePublicObject.validateJsonElement(jsonArrayresults.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CollectionResponseWithTotalSimplePublicObjectForwardPaging.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CollectionResponseWithTotalSimplePublicObjectForwardPaging' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CollectionResponseWithTotalSimplePublicObjectForwardPaging> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CollectionResponseWithTotalSimplePublicObjectForwardPaging.class));

       return (TypeAdapter<T>) new TypeAdapter<CollectionResponseWithTotalSimplePublicObjectForwardPaging>() {
           @Override
           public void write(JsonWriter out, CollectionResponseWithTotalSimplePublicObjectForwardPaging value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CollectionResponseWithTotalSimplePublicObjectForwardPaging read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CollectionResponseWithTotalSimplePublicObjectForwardPaging given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CollectionResponseWithTotalSimplePublicObjectForwardPaging
   * @throws IOException if the JSON string is invalid with respect to CollectionResponseWithTotalSimplePublicObjectForwardPaging
   */
  public static CollectionResponseWithTotalSimplePublicObjectForwardPaging fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CollectionResponseWithTotalSimplePublicObjectForwardPaging.class);
  }

  /**
   * Convert an instance of CollectionResponseWithTotalSimplePublicObjectForwardPaging to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

