/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.github.mike_rollout.JSON;

/**
 * PublicMergeInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-19T16:43:10.955404+03:00[Africa/Nairobi]", comments = "Generator version: 7.7.0")
public class PublicMergeInput {
  public static final String SERIALIZED_NAME_OBJECT_ID_TO_MERGE = "objectIdToMerge";
  @SerializedName(SERIALIZED_NAME_OBJECT_ID_TO_MERGE)
  private String objectIdToMerge;

  public static final String SERIALIZED_NAME_PRIMARY_OBJECT_ID = "primaryObjectId";
  @SerializedName(SERIALIZED_NAME_PRIMARY_OBJECT_ID)
  private String primaryObjectId;

  public PublicMergeInput() {
  }

  public PublicMergeInput objectIdToMerge(String objectIdToMerge) {
    this.objectIdToMerge = objectIdToMerge;
    return this;
  }

  /**
   * Get objectIdToMerge
   * @return objectIdToMerge
   */
  @javax.annotation.Nonnull
  public String getObjectIdToMerge() {
    return objectIdToMerge;
  }

  public void setObjectIdToMerge(String objectIdToMerge) {
    this.objectIdToMerge = objectIdToMerge;
  }


  public PublicMergeInput primaryObjectId(String primaryObjectId) {
    this.primaryObjectId = primaryObjectId;
    return this;
  }

  /**
   * Get primaryObjectId
   * @return primaryObjectId
   */
  @javax.annotation.Nonnull
  public String getPrimaryObjectId() {
    return primaryObjectId;
  }

  public void setPrimaryObjectId(String primaryObjectId) {
    this.primaryObjectId = primaryObjectId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PublicMergeInput publicMergeInput = (PublicMergeInput) o;
    return Objects.equals(this.objectIdToMerge, publicMergeInput.objectIdToMerge) &&
        Objects.equals(this.primaryObjectId, publicMergeInput.primaryObjectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objectIdToMerge, primaryObjectId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicMergeInput {\n");
    sb.append("    objectIdToMerge: ").append(toIndentedString(objectIdToMerge)).append("\n");
    sb.append("    primaryObjectId: ").append(toIndentedString(primaryObjectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("objectIdToMerge");
    openapiFields.add("primaryObjectId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("objectIdToMerge");
    openapiRequiredFields.add("primaryObjectId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PublicMergeInput
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PublicMergeInput.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PublicMergeInput is not found in the empty JSON string", PublicMergeInput.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PublicMergeInput.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PublicMergeInput` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PublicMergeInput.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("objectIdToMerge").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `objectIdToMerge` to be a primitive type in the JSON string but got `%s`", jsonObj.get("objectIdToMerge").toString()));
      }
      if (!jsonObj.get("primaryObjectId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primaryObjectId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primaryObjectId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PublicMergeInput.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PublicMergeInput' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PublicMergeInput> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PublicMergeInput.class));

       return (TypeAdapter<T>) new TypeAdapter<PublicMergeInput>() {
           @Override
           public void write(JsonWriter out, PublicMergeInput value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PublicMergeInput read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PublicMergeInput given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PublicMergeInput
   * @throws IOException if the JSON string is invalid with respect to PublicMergeInput
   */
  public static PublicMergeInput fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PublicMergeInput.class);
  }

  /**
   * Convert an instance of PublicMergeInput to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

