/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AssociationSpec
 */
public class AssociationSpecTest {
    private final AssociationSpec model = new AssociationSpec();

    /**
     * Model tests for AssociationSpec
     */
    @Test
    public void testAssociationSpec() {
        // TODO: test AssociationSpec
    }

    /**
     * Test the property 'associationCategory'
     */
    @Test
    public void associationCategoryTest() {
        // TODO: test associationCategory
    }

    /**
     * Test the property 'associationTypeId'
     */
    @Test
    public void associationTypeIdTest() {
        // TODO: test associationTypeId
    }

}
