/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mike_rollout.model.SimplePublicObject;
import io.github.mike_rollout.model.StandardError;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BatchResponseSimplePublicObjectWithErrors
 */
public class BatchResponseSimplePublicObjectWithErrorsTest {
    private final BatchResponseSimplePublicObjectWithErrors model = new BatchResponseSimplePublicObjectWithErrors();

    /**
     * Model tests for BatchResponseSimplePublicObjectWithErrors
     */
    @Test
    public void testBatchResponseSimplePublicObjectWithErrors() {
        // TODO: test BatchResponseSimplePublicObjectWithErrors
    }

    /**
     * Test the property 'completedAt'
     */
    @Test
    public void completedAtTest() {
        // TODO: test completedAt
    }

    /**
     * Test the property 'numErrors'
     */
    @Test
    public void numErrorsTest() {
        // TODO: test numErrors
    }

    /**
     * Test the property 'requestedAt'
     */
    @Test
    public void requestedAtTest() {
        // TODO: test requestedAt
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
