/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mike_rollout.model.SimplePublicObjectId;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BatchReadInputSimplePublicObjectId
 */
public class BatchReadInputSimplePublicObjectIdTest {
    private final BatchReadInputSimplePublicObjectId model = new BatchReadInputSimplePublicObjectId();

    /**
     * Model tests for BatchReadInputSimplePublicObjectId
     */
    @Test
    public void testBatchReadInputSimplePublicObjectId() {
        // TODO: test BatchReadInputSimplePublicObjectId
    }

    /**
     * Test the property 'propertiesWithHistory'
     */
    @Test
    public void propertiesWithHistoryTest() {
        // TODO: test propertiesWithHistory
    }

    /**
     * Test the property 'idProperty'
     */
    @Test
    public void idPropertyTest() {
        // TODO: test idProperty
    }

    /**
     * Test the property 'inputs'
     */
    @Test
    public void inputsTest() {
        // TODO: test inputs
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

}
