/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mike_rollout.model.ForwardPaging;
import io.github.mike_rollout.model.SimplePublicObjectWithAssociations;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CollectionResponseSimplePublicObjectWithAssociationsForwardPaging
 */
public class CollectionResponseSimplePublicObjectWithAssociationsForwardPagingTest {
    private final CollectionResponseSimplePublicObjectWithAssociationsForwardPaging model = new CollectionResponseSimplePublicObjectWithAssociationsForwardPaging();

    /**
     * Model tests for CollectionResponseSimplePublicObjectWithAssociationsForwardPaging
     */
    @Test
    public void testCollectionResponseSimplePublicObjectWithAssociationsForwardPaging() {
        // TODO: test CollectionResponseSimplePublicObjectWithAssociationsForwardPaging
    }

    /**
     * Test the property 'paging'
     */
    @Test
    public void pagingTest() {
        // TODO: test paging
    }

    /**
     * Test the property 'results'
     */
    @Test
    public void resultsTest() {
        // TODO: test results
    }

}
