/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PublicMergeInput
 */
public class PublicMergeInputTest {
    private final PublicMergeInput model = new PublicMergeInput();

    /**
     * Model tests for PublicMergeInput
     */
    @Test
    public void testPublicMergeInput() {
        // TODO: test PublicMergeInput
    }

    /**
     * Test the property 'objectIdToMerge'
     */
    @Test
    public void objectIdToMergeTest() {
        // TODO: test objectIdToMerge
    }

    /**
     * Test the property 'primaryObjectId'
     */
    @Test
    public void primaryObjectIdTest() {
        // TODO: test primaryObjectId
    }

}
