/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mike_rollout.model.FilterGroup;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PublicObjectSearchRequest
 */
public class PublicObjectSearchRequestTest {
    private final PublicObjectSearchRequest model = new PublicObjectSearchRequest();

    /**
     * Model tests for PublicObjectSearchRequest
     */
    @Test
    public void testPublicObjectSearchRequest() {
        // TODO: test PublicObjectSearchRequest
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'after'
     */
    @Test
    public void afterTest() {
        // TODO: test after
    }

    /**
     * Test the property 'sorts'
     */
    @Test
    public void sortsTest() {
        // TODO: test sorts
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'filterGroups'
     */
    @Test
    public void filterGroupsTest() {
        // TODO: test filterGroups
    }

}
