/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PublicGdprDeleteInput
 */
public class PublicGdprDeleteInputTest {
    private final PublicGdprDeleteInput model = new PublicGdprDeleteInput();

    /**
     * Model tests for PublicGdprDeleteInput
     */
    @Test
    public void testPublicGdprDeleteInput() {
        // TODO: test PublicGdprDeleteInput
    }

    /**
     * Test the property 'idProperty'
     */
    @Test
    public void idPropertyTest() {
        // TODO: test idProperty
    }

    /**
     * Test the property 'objectId'
     */
    @Test
    public void objectIdTest() {
        // TODO: test objectId
    }

}
