/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.mike_rollout.model.PublicAssociationsForObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SimplePublicObjectInputForCreate
 */
public class SimplePublicObjectInputForCreateTest {
    private final SimplePublicObjectInputForCreate model = new SimplePublicObjectInputForCreate();

    /**
     * Model tests for SimplePublicObjectInputForCreate
     */
    @Test
    public void testSimplePublicObjectInputForCreate() {
        // TODO: test SimplePublicObjectInputForCreate
    }

    /**
     * Test the property 'associations'
     */
    @Test
    public void associationsTest() {
        // TODO: test associations
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

}
