/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.api;

import io.github.mike_rollout.ApiException;
import io.github.mike_rollout.model.CollectionResponseSimplePublicObjectWithAssociationsForwardPaging;
import io.github.mike_rollout.model.Error;
import io.github.mike_rollout.model.SimplePublicObject;
import io.github.mike_rollout.model.SimplePublicObjectInput;
import io.github.mike_rollout.model.SimplePublicObjectInputForCreate;
import io.github.mike_rollout.model.SimplePublicObjectWithAssociations;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BasicApi
 */
@Disabled
public class BasicApiTest {

    private final BasicApi api = new BasicApi();

    /**
     * Archive
     *
     * Move an Object identified by &#x60;{contactId}&#x60; to the recycling bin.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteCrmV3ObjectsContactsContactIdArchiveTest() throws ApiException {
        String contactId = null;
        api.deleteCrmV3ObjectsContactsContactIdArchive(contactId);
        // TODO: test validations
    }

    /**
     * Read
     *
     * Read an Object identified by &#x60;{contactId}&#x60;. &#x60;{contactId}&#x60; refers to the internal object ID.  Control what is returned via the &#x60;properties&#x60; query param.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCrmV3ObjectsContactsContactIdGetByIdTest() throws ApiException {
        String contactId = null;
        List<String> properties = null;
        List<String> propertiesWithHistory = null;
        List<String> associations = null;
        Boolean archived = null;
        SimplePublicObjectWithAssociations response = api.getCrmV3ObjectsContactsContactIdGetById(contactId, properties, propertiesWithHistory, associations, archived);
        // TODO: test validations
    }

    /**
     * List
     *
     * Read a page of contacts. Control what is returned via the &#x60;properties&#x60; query param.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCrmV3ObjectsContactsGetPageTest() throws ApiException {
        Integer limit = null;
        String after = null;
        List<String> properties = null;
        List<String> propertiesWithHistory = null;
        List<String> associations = null;
        Boolean archived = null;
        CollectionResponseSimplePublicObjectWithAssociationsForwardPaging response = api.getCrmV3ObjectsContactsGetPage(limit, after, properties, propertiesWithHistory, associations, archived);
        // TODO: test validations
    }

    /**
     * Update
     *
     * Perform a partial update of an Object identified by &#x60;{contactId}&#x60;. &#x60;{contactId}&#x60; refers to the internal object ID. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void patchCrmV3ObjectsContactsContactIdUpdateTest() throws ApiException {
        String contactId = null;
        SimplePublicObjectInput simplePublicObjectInput = null;
        SimplePublicObject response = api.patchCrmV3ObjectsContactsContactIdUpdate(contactId, simplePublicObjectInput);
        // TODO: test validations
    }

    /**
     * Create
     *
     * Create a contact with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard contacts is provided.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCrmV3ObjectsContactsCreateTest() throws ApiException {
        SimplePublicObjectInputForCreate simplePublicObjectInputForCreate = null;
        SimplePublicObject response = api.postCrmV3ObjectsContactsCreate(simplePublicObjectInputForCreate);
        // TODO: test validations
    }

}
