/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.api;

import io.github.mike_rollout.ApiException;
import io.github.mike_rollout.model.BatchInputSimplePublicObjectBatchInput;
import io.github.mike_rollout.model.BatchInputSimplePublicObjectId;
import io.github.mike_rollout.model.BatchInputSimplePublicObjectInputForCreate;
import io.github.mike_rollout.model.BatchReadInputSimplePublicObjectId;
import io.github.mike_rollout.model.BatchResponseSimplePublicObject;
import io.github.mike_rollout.model.BatchResponseSimplePublicObjectWithErrors;
import io.github.mike_rollout.model.Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BatchApi
 */
@Disabled
public class BatchApiTest {

    private final BatchApi api = new BatchApi();

    /**
     * Archive a batch of contacts by ID
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCrmV3ObjectsContactsBatchArchiveArchiveTest() throws ApiException {
        BatchInputSimplePublicObjectId batchInputSimplePublicObjectId = null;
        api.postCrmV3ObjectsContactsBatchArchiveArchive(batchInputSimplePublicObjectId);
        // TODO: test validations
    }

    /**
     * Create a batch of contacts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCrmV3ObjectsContactsBatchCreateCreateTest() throws ApiException {
        BatchInputSimplePublicObjectInputForCreate batchInputSimplePublicObjectInputForCreate = null;
        BatchResponseSimplePublicObject response = api.postCrmV3ObjectsContactsBatchCreateCreate(batchInputSimplePublicObjectInputForCreate);
        // TODO: test validations
    }

    /**
     * Read a batch of contacts by internal ID, or unique property values
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCrmV3ObjectsContactsBatchReadReadTest() throws ApiException {
        BatchReadInputSimplePublicObjectId batchReadInputSimplePublicObjectId = null;
        Boolean archived = null;
        BatchResponseSimplePublicObject response = api.postCrmV3ObjectsContactsBatchReadRead(batchReadInputSimplePublicObjectId, archived);
        // TODO: test validations
    }

    /**
     * Update a batch of contacts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCrmV3ObjectsContactsBatchUpdateUpdateTest() throws ApiException {
        BatchInputSimplePublicObjectBatchInput batchInputSimplePublicObjectBatchInput = null;
        BatchResponseSimplePublicObject response = api.postCrmV3ObjectsContactsBatchUpdateUpdate(batchInputSimplePublicObjectBatchInput);
        // TODO: test validations
    }

}
