/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.api;

import io.github.mike_rollout.ApiException;
import io.github.mike_rollout.model.Error;
import io.github.mike_rollout.model.PublicGdprDeleteInput;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GdprApi
 */
@Disabled
public class GdprApiTest {

    private final GdprApi api = new GdprApi();

    /**
     * GDPR DELETE
     *
     * Permanently delete a contact and all associated content to follow GDPR. Use optional property &#39;idProperty&#39; set to &#39;email&#39; to identify contact by email address. If email address is not found, the email address will be added to a blocklist and prevent it from being used in the future.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCrmV3ObjectsContactsGdprDeletePurgeTest() throws ApiException {
        PublicGdprDeleteInput publicGdprDeleteInput = null;
        api.postCrmV3ObjectsContactsGdprDeletePurge(publicGdprDeleteInput);
        // TODO: test validations
    }

}
