/*
 * Contacts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.mike_rollout.api;

import io.github.mike_rollout.ApiException;
import io.github.mike_rollout.model.Error;
import io.github.mike_rollout.model.PublicMergeInput;
import io.github.mike_rollout.model.SimplePublicObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicObjectApi
 */
@Disabled
public class PublicObjectApiTest {

    private final PublicObjectApi api = new PublicObjectApi();

    /**
     * Merge two contacts with same type
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postCrmV3ObjectsContactsMergeMergeTest() throws ApiException {
        PublicMergeInput publicMergeInput = null;
        SimplePublicObject response = api.postCrmV3ObjectsContactsMergeMerge(publicMergeInput);
        // TODO: test validations
    }

}
